WIP - Update/triple store
BeameryEdge/Skosmos pull request #11
Opened 2023-03-08 17:26 UTC by henrieglesorotos

@namedgraph @vaishalir18 - fiddling around with things between meetings today. This is as far as I get. 

It is still not working atm. Error atm: 

```
[Wed Mar 08 17:23:56.044353 2023] [php7:error] [pid 11] [client 172.22.0.1:64544] PHP Fatal error:  Uncaught EasyRdf\\Http\\Exception: HTTP request for SPARQL query failed in /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php:274\nStack trace:\n#0 /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php(131): EasyRdf\\Sparql\\Client->request()\n#1 /var/www/html/model/sparql/GenericSparql.php(93): EasyRdf\\Sparql\\Client->query()\n#2 /var/www/html/model/sparql/GenericSparql.php(1407): GenericSparql->query()\n#3 /var/www/html/model/Vocabulary.php(522): GenericSparql->queryFirstCharacters()\n#4 /var/www/html/controller/WebController.php(478): Vocabulary->getAlphabet()\n#5 /var/www/html/index.php(81): WebController->invokeAlphabeticalIndex()\n#6 {main}\n  thrown in /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php on line 274, referer: http://localhost:9090/skills/en/
```

2023-03-08 21:25 UTC, henrieglesorotos commented
http should be fixed now @namedgraph ?

2023-03-08 21:26 UTC, namedgraph commented
Looks like. The server name shouldn't make a difference.

You sure Skosmos supports `skosmos:sparqlDialect "Virtuoso"`?

2023-03-08 21:27 UTC, henrieglesorotos commented
Latest erros - 

```
skosmos-web | [Wed Mar 08 21:21:29.086454 2023] [php7:warn] [pid 12] [client 172.22.0.1:55216] PHP Warning:  Declaration of VirtuosoSparql::generateAlphabeticalListQuery($letter, $lang, $limit, $offset, $classes, $showDeprecated = false) should be compatible with GenericSparql::generateAlphabeticalListQuery($letter, $lang, $limit, $offset, $classes, $showDeprecated = false, $qualifier = NULL) in /var/www/html/model/sparql/VirtuosoSparql.php on line 23, referer: http://localhost:9090/skills/en/

skosmos-web | 172.22.0.1 - - [08/Mar/2023:21:21:29 +0000] "GET /rest/v1/skills/labelStatistics?lang=en HTTP/1.1" 500 261 "http://localhost:9090/skills/en/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"

skosmos-web | [Wed Mar 08 21:21:29.098545 2023] [php7:error] [pid 12] [client 172.22.0.1:55216] PHP Fatal error:  Uncaught EasyRdf\\Http\\Exception: HTTP request for SPARQL query failed in /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php:274\nStack trace:\n#0 /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php(131): EasyRdf\\Sparql\\Client->request()\n#1 /var/www/html/model/sparql/GenericSparql.php(93): EasyRdf\\Sparql\\Client->query()\n#2 /var/www/html/model/sparql/GenericSparql.php(1407): GenericSparql->query()\n#3 /var/www/html/model/Vocabulary.php(522): GenericSparql->queryFirstCharacters()\n#4 /var/www/html/controller/WebController.php(478): Vocabulary->getAlphabet()\n#5 /var/www/html/index.php(81): WebController->invokeAlphabeticalIndex()\n#6 {main}\n  thrown in /var/www/html/vendor/sweetrdf/easyrdf/lib/Sparql/Client.php on line 274, referer: http://localhost:9090/skills/en/
```

2023-03-08 21:28 UTC, henrieglesorotos commented
> 

I mean, I'm not 100% sure. Looking at this - https://groups.google.com/g/skosmos-users/c/OsAFT_OINb8/m/aHwf_fx4BgAJ. This was way before the repo was dockerised tho.

2023-03-08 21:46 UTC, namedgraph commented
Have you tried:
> "Generic" for plain SPARQL 1.1`

2023-03-08 21:48 UTC, henrieglesorotos commented
> Have you tried:
> 
> > "Generic" for plain SPARQL 1.1`

That's what I'm trying now. Suggests here is the issue - https://github.com/BeameryEdge/Skosmos/blob/update/triple-store/model/sparql/GenericSparql.php#L1407

2023-03-08 21:56 UTC, namedgraph commented
No idea if related but I was looking at this at some point: https://github.com/NatLibFi/Skosmos/issues/632

Virtuoso could well be buggy.

2023-03-08 21:58 UTC, namedgraph commented
Also this: https://groups.google.com/g/skosmos-users/c/11ROK0C7NyU/m/iGv5mL3hCgAJ

2023-03-08 22:02 UTC, henrieglesorotos commented
Just noticed I need to change the sparql endpoint in the vocab configs too. Trying that.

2023-03-09 18:45 UTC, namedgraph commented
Delete `dockerfiles/config/skosmos.ttl`? It's Fuseki-specific.

2023-03-10 09:01 UTC, henrieglesorotos commented
> Delete `dockerfiles/config/skosmos.ttl`? It's Fuseki-specific.

Sure - Will give that a go.

2023-03-10 09:37 UTC, namedgraph requested changes

2023-03-10 09:44 UTC, namedgraph commented on dockerfiles/docker-compose.yml
> +      SPARQL_UPDATE: "true"
Or just remove the `SPARQL_UPDATE` setting altogether to make the endpoint read-only

2023-03-10 09:51 UTC, namedgraph approved these changes

2023-03-10 09:52 UTC, merged